
main: main.cpp BigNumber.cpp BigNumber.hpp FiniteFieldElement.cpp FiniteFieldElement.hpp Point.cpp Point.hpp EllipticCurve.cpp EllipticCurve.hpp
	g++ main.cpp BigNumber.cpp FiniteFieldElement.cpp Point.cpp EllipticCurve.cpp -o homework4 
	

clean: 
	rm main
